### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mambolevis** [novoid/dot-emacs#1]
Hi,

I am trying to config pylookup in emacs for python.3.5.3 in Windows. Please let me ask you some
questions.

1.  Is pylookup able to work with any python version?
2. How can I generate the pylookup.db in windows?
I tested with MINGW64:

```
$ ./pylookup.py -u python-3.5.3-docs-html
Wait for a few seconds...
Fetching index from 'file://C:/home_frey/.emacs.d/user/site-lisp/pylookup/python-3.5.3-docs-html/genindex-all.html'
Error: fetching file from 'file://C:/home_frey/.emacs.d/user/site-lisp/pylookup/python-3.5.3-docs-html/genindex-all.html'
Wait for a few seconds...
Fetching index from 'file://C:/home_frey/.emacs.d/user/site-lisp/pylookup/python-3.5.3-docs-html/genindex.html'
Error: fetching file from 'file://C:/home_frey/.emacs.d/user/site-lisp/pylookup/python-3.5.3-docs-html/genindex.html'
Failed to load index for input 'file://C:/home_frey/.emacs.d/user/site-lisp/pylookup/python-3.5.3-docs-html'

```
The pylookup.db is generated but with 0KB (empty)

3. In emacs I setup the enviroment variable to see pylookup.py. Nontheless, when I execute `pylookup-lookup-at-point` the following message appears:
`Searching for program: No such file or directory, pylookup.py`

Thank for your time

**Comment by novoid** [comment]
Sorry, I am using Python environments on GNU/Linux only at this moment.
Therefore, I have no clue how to do it because on GNU/Linux this worked flawlessly.
