### ISSUE TITLE
org-agenda-category-alist fix

### ISSUE THREAD

**Issue by Plisp** [novoid/dot-emacs#2]
Backquote syntax is the answer to your problems :)

```
(add-to-list 'org-agenda-category-icon-alist
  `("detego" ,(concat my-user-emacs-directory "bin/detego-inwarehouse-logo-D_only_16x16.png") nil nil :ascent center))
```

**Comment by novoid** [comment]
Wonderful!
I just committed 7fc487bc91ba8468c5add7674f87f56c460c2ee6 which is fixing this annoying thing.
Thanks for your help!
